// Native Electron integration test. Invoked only by --smoke-test in an isolated profile.
const assert = require('node:assert/strict');
const { readFile, writeFile } = require('node:fs/promises');
const path = require('node:path');
const http = require('node:http');
exports.run = async (window, store, directory) => {
  const { demoPlan } = await import('../public/demo.js');
  const { cardPathFor } = await import('./knowledge-cards.mjs');
  const evaluate = code => window.webContents.executeJavaScript(code).catch(error => { console.error('SMOKE_FAILED_STEP', code.slice(0, 220)); throw error; });
  const wait = expression => evaluate(`new Promise((resolve, reject) => { let attempts = 0; const timer = setInterval(() => { try { if (${expression}) { clearInterval(timer); resolve(true); } else if (++attempts > 150) { clearInterval(timer); reject(new Error('Desktop check timed out')); } } catch (error) { clearInterval(timer); reject(error); } }, 100); })`);
  await wait("document.querySelector('main h1')");
  const localSettings = { provider: 'ollama', model: '', baseUrl: '', keyAction: 'clear', apiKey: '', localOnly: true, jsonMode: 'auto', timeoutMs: 120000, maxTokens: 8192 };
  const { imageDefaults } = await import('../image-model.mjs');
  const { speechDefaults } = await import('../public/speech.js');
  await evaluate(`window.learnflowDesktop.saveSpeechSettings(${JSON.stringify({...speechDefaults,keyAction:'clear',apiKey:''})})`);
  await evaluate(`window.learnflowDesktop.saveImageSettings(${JSON.stringify({...imageDefaults,keyAction:'clear',apiKey:''})})`);
  await evaluate('window.learnflowDesktop.saveWebSearchSettings({enabled:false})');
  await evaluate(`window.learnflowDesktop.saveSettings(${JSON.stringify(localSettings)})`);
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  assert.deepEqual(await evaluate("({ bridge: typeof window.learnflowDesktop?.saveSettings, node: typeof window.require })"), { bridge: 'function', node: 'undefined' });
  // Exercise settings through the real form and IPC bridge.
  await evaluate("document.querySelector('[data-page=settings]').click()");
  await wait("document.querySelector('#desktop-settings-form')");
  assert.equal(await evaluate("document.querySelectorAll('.model-settings-grid > .model-settings-card').length"), 3);
  assert.equal(await evaluate("document.querySelectorAll('select[name=keyAction]').length"), 0);
  assert.equal(await evaluate("[...document.querySelectorAll('.model-advanced')].every(item => !item.open)"), true);
  // Exercise the keyless consent form through actual click/change/submit events.
  const beforeSearchSave = await evaluate("document.querySelector('#connection-result').textContent");
  await evaluate("document.querySelector('#web-search-settings-form [name=enabled]').click();document.querySelector('#web-search-settings-form').requestSubmit()");
  await wait("document.querySelector('#web-search-settings-result')?.textContent.includes('已启用并保存')");
  assert.deepEqual(JSON.parse(await readFile(path.join(directory, 'web-search-settings.json'), 'utf8')), {version:1,enabled:true});
  assert.equal(await evaluate("document.querySelector('#connection-result').textContent"), beforeSearchSave);
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  await evaluate("document.querySelector('[data-page=settings]').click()");
  await wait("document.querySelector('#web-search-settings-form')");
  assert.equal(await evaluate("document.querySelector('#web-search-settings-form [name=enabled]').checked"), true);
  await evaluate("document.querySelector('#web-search-settings-form [name=enabled]').click();document.querySelector('#web-search-settings-form').requestSubmit()");
  await wait("document.querySelector('#web-search-settings-result')?.textContent.includes('已关闭并保存')");
  assert.equal(JSON.parse(await readFile(path.join(directory, 'web-search-settings.json'), 'utf8')).enabled, false);
  console.log('WEB_SEARCH_SETTINGS_SMOKE', JSON.stringify({passed:true,checks:['keyless-checkbox-events','enable-save-file','reload-consent','disable-save-file','other-model-status-unchanged']}));
  // Pending fields (including a new secret) stay only in memory when another card saves.
  await evaluate("document.querySelector('#image-model-name').value='pending-image-model';document.querySelector('#image-model-name').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#image-model-key').value='pending-image-key-not-real';document.querySelector('#image-model-key').dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#image-settings-form .model-advanced').open=true;document.querySelector('#speech-voice').value='pending-voice';document.querySelector('#speech-voice').dispatchEvent(new Event('input',{bubbles:true}))");
  await evaluate("document.querySelector('#model-name').value = 'desktop-smoke-model'; document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  const saved = JSON.parse(await readFile(path.join(directory, 'settings.json'), 'utf8'));
  assert.equal(saved.model, 'desktop-smoke-model'); assert.equal(saved.localOnly, true);
  assert.equal(await evaluate("document.querySelector('#model-name').value"), 'desktop-smoke-model');
  assert.equal(await evaluate("document.querySelector('#image-model-name').value"), 'pending-image-model');
  assert.equal(await evaluate("document.querySelector('#image-model-key').value"), 'pending-image-key-not-real');
  assert.equal(await evaluate("document.querySelector('#image-settings-form .model-advanced').open"), true);
  assert.equal(await evaluate("document.querySelector('#speech-voice').value"), 'pending-voice');
  assert.equal(await evaluate("document.querySelector('[data-action=check-speech-connection]').disabled"), true);
  assert.ok(!(await readFile(path.join(directory, 'image-settings.json'), 'utf8')).includes('pending-image-key-not-real'));
  assert.ok(!(await readFile(path.join(directory, 'settings.json'), 'utf8')).includes('pending-image-key-not-real'));
  // Save a test-only local key, assert OS encryption, then clear it.
  await evaluate("document.querySelector('#model-key').value = 'smoke-only-not-a-real-key'; document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#model-key')?.placeholder.includes('留空保留') && document.querySelector('#model-key')?.value === ''");
  const encrypted = await readFile(path.join(directory, 'settings.json'), 'utf8');
  assert.ok(!encrypted.includes('smoke-only-not-a-real-key'));
  assert.ok(JSON.parse(encrypted).encryptedApiKey.length > 0);
  await evaluate("document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  assert.equal(store.getSettings().hasApiKey, true, 'a blank key input must keep the saved key');
  await evaluate("document.querySelector('#desktop-settings-form [data-action=clear-model-key]').click()");
  assert.equal(await evaluate("document.querySelector('#key-action').value"), 'clear');
  await evaluate("document.querySelector('#desktop-settings-form [data-action=clear-model-key]').click()");
  assert.equal(await evaluate("document.querySelector('#key-action').value"), 'keep');
  await evaluate("document.querySelector('#desktop-settings-form [data-action=clear-model-key]').click(); document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#model-key')?.placeholder.includes('有就填写')");
  assert.equal(store.getSettings().hasApiKey, false);
  assert.equal(store.getSettings().model, 'desktop-smoke-model');
  assert.equal(await evaluate("document.querySelector('#model-name').value"), 'desktop-smoke-model');
  await writeFile(path.join(directory, '..', 'unified-settings-smoke.png'), (await window.webContents.capturePage()).toPNG());
  // Reproduce the reported conflict using a cloud preset, without making cloud requests.
  await evaluate("document.querySelector('#model-provider').value = 'deepseek'; document.querySelector('#model-provider').dispatchEvent(new Event('change', {bubbles:true})); document.querySelector('#model-name').value = 'smoke-cloud-model'; document.querySelector('#desktop-settings-form [name=localOnly]').checked = true; document.querySelector('#model-key').value = 'smoke-cloud-key-not-real'; document.querySelector('#model-key').dispatchEvent(new Event('input', {bubbles:true})); document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#remote-permission')?.hidden === false");
  assert.match(await evaluate("document.querySelector('#settings-error').textContent"), /仅使用本机模型/);
  assert.equal(store.getSettings().provider, 'ollama', 'rejected draft must not change saved configuration');
  assert.equal(await evaluate("document.querySelector('[data-action=test-connection]').disabled"), true);
  await evaluate("document.querySelector('[data-action=allow-remote-save]').click()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  assert.equal(store.getSettings().provider, 'deepseek');
  assert.equal(store.getSettings().localOnly, false);
  assert.equal(store.getSettings().hasApiKey, true);
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  const cloud = await evaluate('window.learnflowDesktop.load()');
  assert.equal(cloud.settings.provider, 'deepseek');
  assert.equal(cloud.settings.localOnly, false);
  assert.equal(cloud.settings.hasApiKey, true);
  await evaluate("document.querySelector('[data-page=settings]').click()");
  // Cover the same issue for self-hosted services on another LAN machine.
  await evaluate("document.querySelector('#model-provider').value='ollama';document.querySelector('#model-provider').dispatchEvent(new Event('change',{bubbles:true}))");
  assert.equal(await evaluate("document.querySelector('#model-name').value"), 'desktop-smoke-model');
  assert.equal(await evaluate("document.querySelector('#desktop-settings-form [name=localOnly]').checked"), true);
  assert.equal(await evaluate("document.querySelector('#model-key').value"), '');
  assert.equal(store.getSettings().provider, 'deepseek', 'selection alone must not activate another service');
  await evaluate("document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  assert.equal(store.getSettings().provider, 'ollama');
  await evaluate("document.querySelector('#model-provider').value='deepseek';document.querySelector('#model-provider').dispatchEvent(new Event('change',{bubbles:true}))");
  assert.equal(await evaluate("document.querySelector('#model-name').value"), 'smoke-cloud-model');
  assert.equal(await evaluate("document.querySelector('#desktop-settings-form [name=localOnly]').checked"), false);
  assert.equal(await evaluate("document.querySelector('#model-key').value"), '');
  assert.match(await evaluate("document.querySelector('#model-key').placeholder"), /已保存/);
  await evaluate("document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  assert.equal(store.getSettings().provider, 'deepseek'); assert.equal(store.getSettings().hasApiKey, true);
  assert.ok(!JSON.stringify(await evaluate('window.learnflowDesktop.load()')).includes('smoke-cloud-key-not-real'));
  console.log('MODEL_PROFILE_SMOKE', JSON.stringify({passed:true,checks:['switch-restores-parameters','selection-does-not-activate','local-and-cloud-key-isolation','saved-key-reused-with-empty-input','reload-retains-service-profiles']}));
  await evaluate("document.querySelector('#model-provider').value = 'vllm'; document.querySelector('#model-provider').dispatchEvent(new Event('change', {bubbles:true})); document.querySelector('#model-name').value = 'smoke-lan-model'; document.querySelector('#model-url').value = 'http://192.168.1.2:8000/v1'; document.querySelector('[name=localOnly]').checked = true; document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#remote-permission')?.hidden === false");
  assert.equal(store.getSettings().provider, 'deepseek');
  await evaluate("document.querySelector('[data-action=allow-remote-save]').click()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  assert.equal(store.getSettings().provider, 'vllm');
  assert.equal(store.getSettings().hasApiKey, false);
  // Return the isolated test profile to a local-only model for the learning checks.
  await evaluate("document.querySelector('#model-provider').value = 'ollama'; document.querySelector('#model-provider').dispatchEvent(new Event('change', {bubbles:true})); document.querySelector('#model-name').value = 'desktop-smoke-model'; document.querySelector('[name=localOnly]').checked = true; document.querySelector('#desktop-settings-form').requestSubmit()");
  await wait("document.querySelector('#connection-result')?.textContent.includes('配置已保存并生效')");
  // Complete a sample lesson, generate a Wiki card, and persist it on disk.
  // A previous smoke run may have left its custom test route active.
  await evaluate("window.learnflowDesktop.saveAnnotations('p1', [])");
  await evaluate(`window.learnflowDesktop.setActivePlan(${JSON.stringify(demoPlan.id)})`);
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  await evaluate("document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id=p1]').click()");
  await wait("document.querySelector('[data-tab=quiz]')");
  await evaluate("window.scrollTo(0, 350); new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  const quickAskPosition = await evaluate("(() => { const quick = document.querySelector('.quick-ask-button').getBoundingClientRect(), lesson = document.querySelector('.lesson-content').getBoundingClientRect(); return {left:quick.left,right:quick.right,top:quick.top,bottom:quick.bottom,width:quick.width,height:quick.height,lessonRight:lesson.right,viewportWidth:innerWidth,viewportHeight:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollTop:scrollY}; })()");
  const speechDockPosition = await evaluate("(() => { const speech = document.querySelector('.quick-speech-button').getBoundingClientRect(); return {top:speech.top,right:speech.right,width:speech.width,height:speech.height}; })()");
  assert.ok(quickAskPosition.left >= quickAskPosition.lessonRight && quickAskPosition.right <= quickAskPosition.viewportWidth, JSON.stringify(quickAskPosition));
  assert.ok(speechDockPosition.top > quickAskPosition.bottom && speechDockPosition.right <= quickAskPosition.viewportWidth, 'AI 朗读应位于 AI 答疑下方');
  assert.equal(speechDockPosition.width, quickAskPosition.width, 'AI 朗读与 AI 答疑应同宽');
  assert.equal(speechDockPosition.height, quickAskPosition.height, 'AI 朗读与 AI 答疑应同高');
  assert.ok(quickAskPosition.scrollWidth <= quickAskPosition.viewportWidth + 1, JSON.stringify(quickAskPosition));
  assert.ok(Math.abs((quickAskPosition.top + quickAskPosition.bottom) / 2 - quickAskPosition.viewportHeight / 2) < 110);
  await writeFile(path.join(directory, '..', 'quick-ask-smoke.png'), (await window.webContents.capturePage()).toPNG());
  const originalSize = window.getSize();
  window.setSize(900, originalSize[1]);
  await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.quick-ask-dock')).position"), 'fixed');
  assert.equal(await evaluate("document.querySelector('.quick-ask-button').getBoundingClientRect().right <= innerWidth"), true);
  window.setSize(...originalSize);
  await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  await evaluate("document.querySelector('[data-action=quick-ask]').click()");
  await wait("document.querySelector('#lesson-question') && document.querySelector('.study-chat')");
  assert.equal(await evaluate("document.activeElement?.id"), 'lesson-question');
  await evaluate("document.querySelector('[data-action=back-to-reading]').click()");
  await wait("document.querySelector('.lesson-intro')");
  assert.ok(Math.abs((await evaluate('scrollY')) - quickAskPosition.scrollTop) <= 2, 'returning from Q&A should restore the reading scroll position');
  await evaluate("document.querySelector('[data-action=toggle-syllabus]').click()");
  assert.equal(await evaluate("document.querySelector('#course-syllabus').hidden"), true);
  await evaluate("document.querySelector('[data-action=toggle-syllabus]').click()");
  assert.equal(await evaluate("document.querySelector('#course-syllabus').hidden"), false);
  await evaluate("(() => { const text = document.querySelector('.reading-section .annotatable').firstChild; const range = document.createRange(); range.setStart(text, 0); range.setEnd(text, 4); getSelection().removeAllRanges(); getSelection().addRange(range); document.dispatchEvent(new PointerEvent('pointerup', { bubbles: true })); })()");
  await wait("!document.querySelector('#annotation-quick-add').hidden");
  await evaluate("document.querySelector('#annotation-quick-add').click(); document.querySelector('#annotation-text').value = '这是我的桌面测试笔记'; document.querySelector('#annotation-form').requestSubmit()");
  await wait("document.querySelector('.annotation-marker') && !document.querySelector('#annotation-dialog').open");
  assert.equal(await evaluate("window.learnflowDesktop.getLesson('p1').then(item => item.annotations[0].text)"), '这是我的桌面测试笔记');
  await evaluate("document.querySelector('.annotation-marker').click()");
  assert.equal(await evaluate("document.querySelector('#annotation-text').value"), '这是我的桌面测试笔记');
  await evaluate("document.querySelector('[data-action=close-annotation]').click()");
  await evaluate("document.querySelector('[data-tab=quiz]').click(); document.querySelector('[name=q0][value=\"1\"]').checked = true; document.querySelector('[name=q1][value=\"1\"]').checked = true; document.querySelector('#quiz-form').requestSubmit()");
  await wait("document.querySelector('.quiz-result.passed')");
  const reflectionMarkdown = '## 桌面集成测试心得\n\n**掌握核心概念**。';
  await evaluate(`window.learnflowDesktop.saveReflection('p1', ${JSON.stringify(reflectionMarkdown)})`);
  assert.equal(await evaluate("document.querySelector('[data-tab=notes]')"), null);
  assert.equal(await evaluate("document.querySelector('#reflection')"), null);
  const notesBeforeDraft = (await store.loadState()).notes.length;
  await evaluate("document.querySelector('.quiz-result [data-action=create-note]').click()");
  await wait("document.querySelector('#knowledge-draft-form')");
  assert.equal((await store.loadState()).notes.length, notesBeforeDraft, 'an unconfirmed draft must not be saved');
  assert.equal(await evaluate("document.querySelector('#draft-content').value.includes('这是我的桌面测试笔记')"), true);
  await evaluate("document.querySelector('#knowledge-draft-form').requestSubmit()");
  await wait("document.querySelector('#note-form')");
  assert.equal(await evaluate("document.querySelector('#note-source-view').hidden"), true);
  assert.equal(await evaluate("document.querySelector('#note-preview-view').hidden"), false);
  const editedNote = '## 学习要点\n\n**输入与输出**是程序与用户交互的起点。\n\n1. 输入一条语句\n2. 观察输出\n\n```python\nprint("你好")\n```';
  await evaluate(`document.querySelector('#note-edit-switch').click(); document.querySelector('#note-summary').value = '**知识卡片摘要**'; document.querySelector('#note-content').value = ${JSON.stringify(editedNote)}; document.querySelector('#note-read-switch').click()`);
  assert.equal(await evaluate("document.querySelector('#note-preview-content h3').textContent"), '学习要点');
  assert.equal(await evaluate("document.querySelector('#note-preview-content strong').textContent"), '输入与输出');
  assert.equal(await evaluate("document.querySelector('#note-preview-summary')"), null);
  assert.equal(await evaluate("document.querySelector('#note-preview-boundaries')"), null);
  await evaluate("document.querySelector('#note-edit-switch').click()");
  assert.equal(await evaluate("document.querySelector('#note-content').value"), editedNote);
  await evaluate("document.querySelector('#note-form').requestSubmit()");
  await wait("document.querySelector('#toast').textContent.includes('知识卡片已保存') && !document.querySelector('#note-save').disabled");
  await evaluate("document.querySelector('#note-read-switch').click()");
  await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
  await writeFile(path.join(directory, '..', 'note-markdown-smoke.png'), (await window.webContents.capturePage()).toPNG());
  await store.flush();
  const state = await store.loadState();
  assert.equal(state.progress.p1.completed, true);
  assert.equal(state.reflections.p1, reflectionMarkdown);
  assert.ok(state.notes.some(note => note.lessonId === 'p1'));
  assert.equal(state.notes.find(note => note.lessonId === 'p1').content, editedNote);
  const savedNote = state.notes.find(note => note.lessonId === 'p1');
  const savedMarkdown = await readFile(cardPathFor(directory, savedNote), 'utf8');
  assert.match(savedMarkdown, /^---\nschema: 1\n/);
  assert.ok(savedMarkdown.includes(editedNote));
  assert.equal(await evaluate(`window.learnflowDesktop.cardMarkdown(${JSON.stringify(savedNote.id)})`), savedMarkdown);
  assert.ok(await evaluate("document.querySelector('[data-action=delete-note]')"));
  await evaluate("document.querySelector('[data-action=close-note]').click()");
  await wait("document.querySelector('.wiki-tree')");
  assert.ok(await evaluate("document.querySelectorAll('.wiki-tree-card').length") >= 1);
  assert.ok(await evaluate("document.querySelector('[data-action=open-organize]')"));
  await evaluate("document.querySelector('[data-action=open-organize]').click()");
  await wait("document.querySelector('#knowledge-organize-manual-form')");
  assert.equal(await evaluate("document.querySelector('#knowledge-organize-dialog').open"), true);
  await evaluate("document.querySelector('[data-action=close-organize]').click()");
  const wikiHeaderMetrics = "(() => { const title = document.querySelector('.page-intro h1'), tabs = document.querySelector('.wiki-view-switch'); return { titleTop: Math.round(title.getBoundingClientRect().top), titleLeft: Math.round(title.getBoundingClientRect().left), titleSize: getComputedStyle(title).fontSize, tabsTop: Math.round(tabs.getBoundingClientRect().top), tabsLeft: Math.round(tabs.getBoundingClientRect().left) }; })()";
  const treeHeader = await evaluate(wikiHeaderMetrics);
  assert.equal(await evaluate("document.querySelector('#ask-form')"), null);
  await evaluate("document.querySelector('[data-view=chat]').click()");
  await wait("document.querySelector('#ask-form')");
  assert.deepEqual(await evaluate(wikiHeaderMetrics), treeHeader);
  assert.equal(await evaluate("document.querySelector('#note-results').getAttribute('aria-label')"), '知识问答');
  assert.equal(await evaluate("document.querySelector('.wiki-banner')"), null);
  assert.equal(await evaluate("document.querySelector('.wiki-tree')"), null);
  await evaluate("document.querySelector('[data-view=graph]').click()");
  await wait("document.querySelector('#knowledge-graph-svg .graph-node-card')");
  assert.deepEqual(await evaluate(wikiHeaderMetrics), treeHeader);
  assert.ok(await evaluate("document.querySelectorAll('#knowledge-graph-svg .graph-node-card').length") >= 1);
  assert.equal(await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card').classList.contains('graph-isolated')"), false);
  assert.equal(await evaluate("(() => { const node = document.querySelector('#knowledge-graph-svg .graph-node-card'); const sample = document.createElement('span'); sample.style.color = getComputedStyle(node).getPropertyValue('--node-color'); node.append(sample); const expected = getComputedStyle(sample).color; sample.remove(); return getComputedStyle(node.querySelector('circle')).fill === expected; })()"), true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.knowledge-graph')).backgroundColor"), 'rgb(255, 255, 255)');
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.graph-toolbar')).backgroundColor"), 'rgb(255, 255, 255)');
  assert.equal(await evaluate("getComputedStyle(document.querySelector('.graph-node text')).fill"), 'rgb(63, 53, 80)');
  assert.match(await evaluate("getComputedStyle(document.querySelector('#knowledge-graph-svg')).cursor"), /crosshair/);
  assert.match(await evaluate("getComputedStyle(document.querySelector('#knowledge-graph-svg .graph-node-card')).cursor"), /crosshair/);
  assert.ok(await evaluate("document.querySelector('#graph-type') && document.querySelector('#graph-relation') && document.querySelector('[data-action=graph-pause]')"));
  await evaluate("new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
  await writeFile(path.join(directory, '..', 'knowledge-graph-smoke.png'), (await window.webContents.capturePage()).toPNG());
  await evaluate("document.querySelector('[data-action=graph-pause]').click()");
  await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card').dispatchEvent(new PointerEvent('pointerover', { bubbles: true }))");
  assert.equal(await evaluate("document.querySelector('#knowledge-graph-svg').classList.contains('has-focus')"), true);
  await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card').dispatchEvent(new PointerEvent('pointerout', { bubbles: true }))");
  assert.equal(await evaluate("document.querySelector('#knowledge-graph-svg').classList.contains('has-focus')"), false);
  const beforeDrag = await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card circle').getAttribute('cx')");
  await evaluate("(() => { const circle = document.querySelector('#knowledge-graph-svg .graph-node-card circle'); const box = circle.getBoundingClientRect(); const x = box.left + box.width / 2, y = box.top + box.height / 2; circle.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, clientX: x, clientY: y })); document.dispatchEvent(new PointerEvent('pointermove', { bubbles: true, clientX: x + 35, clientY: y + 20 })); document.dispatchEvent(new PointerEvent('pointerup', { bubbles: true, clientX: x + 35, clientY: y + 20 })); })()");
  assert.notEqual(await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card circle').getAttribute('cx')"), beforeDrag);
  await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card').dispatchEvent(new MouseEvent('click', {bubbles:true,cancelable:true}))");
  await wait("document.querySelector('.graph-selection [data-action=open-note]')");
  await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card.selected').dispatchEvent(new MouseEvent('click', {bubbles:true,cancelable:true}))");
  assert.equal(await evaluate("document.querySelector('#knowledge-graph-svg').classList.contains('has-focus')"), false);
  assert.equal(await evaluate("document.querySelector('.graph-selection [data-action=open-note]')"), null);
  await evaluate("document.querySelector('#knowledge-graph-svg .graph-node-card').dispatchEvent(new MouseEvent('click', {bubbles:true,cancelable:true}))");
  await wait("document.querySelector('.graph-selection [data-action=open-note]')");
  const graphBox = await evaluate("document.querySelector('#knowledge-graph-svg').getAttribute('viewBox')");
  await evaluate("document.querySelector('[data-action=graph-zoom-in]').click()");
  assert.notEqual(await evaluate("document.querySelector('#knowledge-graph-svg').getAttribute('viewBox')"), graphBox);
  assert.ok(await evaluate("document.querySelector('.knowledge-graph') && document.querySelector('#knowledge-graph-svg')"));
  await evaluate("document.querySelector('.graph-selection [data-action=open-note]').click()");
  await wait("document.querySelector('#note-preview-view')");
  // Reload the entire renderer, mimicking a new launch while preserving disk data.
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  const loaded = await evaluate('window.learnflowDesktop.load()');
  assert.equal(loaded.state.progress.p1.completed, true);
  assert.equal(loaded.settings.model, 'desktop-smoke-model');
  assert.equal(loaded.settings.apiKey, undefined);
  // Exercise the complete lesson Q&A path against a local mock model.
  const requests = [];
  const imageRequests = [];
  const nativeRequests = [];
  let nativeDownloads = 0, nativeChecks = 0;
  let failNextNativeDownload = false;
  const imageBitmap = Buffer.alloc(64 * 64 * 4);
  for (let pixel = 0; pixel < 64 * 64; pixel++) { imageBitmap[pixel * 4] = 220; imageBitmap[pixel * 4 + 1] = 170; imageBitmap[pixel * 4 + 2] = 110; imageBitmap[pixel * 4 + 3] = 255; }
  const testPng = require('electron').nativeImage.createFromBitmap(imageBitmap, {width:64,height:64}).toPNG();
  const planningQuestionnaire = { summary:'你希望用 Python 整理文件，需要先明确成果与练习方式。', questions:[
    {question:'你想优先整理哪类文件？',why:'选择贴近工作的案例。',type:'single',options:[{label:'本地文档',description:'按类型与日期整理。'},{label:'图片素材',description:'按项目整理和命名。'}]},
    {question:'你希望达成什么成果？',why:'帮助设计验收任务。',type:'multiple',options:[{label:'独立完成小工具',description:'先预览再执行，避免误操作。'},{label:'理解关键代码',description:'能够解释并修改规则。'}]}
  ] };
  const chatMarkdown = '## 直接回答\n\n**输出**会把内容显示给用户。\n\n```python\nprint("你好")\n```';
  const wikiMarkdown = '## 核心概念\n\n**现金流**表示一定期间的现金收入与支出。\n\n### 实践检查\n\n- 确认时间范围\n- 比较收入与支出';
  const model = http.createServer(async (req, res) => {
    if (req.url === '/v1/models') { res.writeHead(200, {'Content-Type':'application/json'}); res.end(JSON.stringify({data:[{id:'smoke-image-model'}]})); return; }
    if (req.url.startsWith('/api/v1/models?')) {
      nativeChecks++; assert.equal(req.headers.authorization,'Bearer smoke-native-key-not-real');
      assert.equal(new URL(req.url,'http://localhost').searchParams.get('model'),'wan2.7-image-pro');
      res.writeHead(200,{'Content-Type':'application/json'});
      res.end(JSON.stringify({success:true,code:null,output:{models:[{model:'wan2.7-image-pro',capabilities:['IG']}]}}));return;
    }
    if (req.url.startsWith('/native-result.png')) {
      nativeDownloads++; assert.equal(req.headers.authorization,undefined); assert.equal(req.headers.cookie,undefined);
      if (failNextNativeDownload) { failNextNativeDownload=false; res.writeHead(503);res.end('mock download unavailable');return; }
      res.writeHead(200,{'Content-Type':'image/png'});res.end(testPng);return;
    }
    const chunks = [];
    for await (const chunk of req) chunks.push(chunk);
    const payload = JSON.parse(Buffer.concat(chunks).toString('utf8'));
    if (req.url === '/api/v1/services/aigc/multimodal-generation/generation') {
      nativeRequests.push(payload);assert.equal(req.headers.authorization,'Bearer smoke-native-key-not-real');
      assert.deepEqual(payload.parameters,{n:1,size:'1024*1024'});assert.equal(payload.response_format,undefined);
      const prompt=payload.input.messages[0].content[0].text;
      const failed=prompt==='原生故障测试';
      if (prompt==='下载故障测试') failNextNativeDownload=true;
      res.writeHead(failed ? 400 : 200,{'Content-Type':'application/json'});
      res.end(JSON.stringify(failed ? {code:'InvalidParameter',message:'private upstream prompt smoke-native-key-not-real',request_id:'12345678-abcd-1234-abcd-1234567890ab'} : {output:{choices:[{message:{role:'assistant',content:[{text:'mock explanation'},{image:`http://127.0.0.1:${model.address().port}/native-result.png?Signature=private-mock-signature`,type:'image'}]}}]}}));return;
    }
    if (req.url === '/v1/images/generations') {
      imageRequests.push(payload);
      assert.equal(req.headers.authorization, 'Bearer smoke-image-key-not-real');
      res.writeHead(payload.prompt === '故障测试' ? 503 : 200, {'Content-Type':'application/json'});
      res.end(JSON.stringify(payload.prompt === '故障测试' ? {error:'mock failure'} : {data:[{b64_json:testPng.toString('base64')}]})); return;
    }
    requests.push({ path: req.url, payload });
    const input = JSON.parse(payload.messages[1].content);
    if (input.revisionRequest === '测试模型不可用') {
      res.writeHead(503, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({error:{message:'Test-only unavailable model'}})); return;
    }
    // Deliberately keep legacy fences in test-only output: they must remain inert code, not drawings.
    const markdownAnswer = ['## 核心结论', '', '**剩余现金 40 元**：收入 100 元，减去支出 60 元。', '', '### 计算步骤', '', '1. 从收支表中找到收入。', '2. 减去支出，得到剩余现金。', '', '> 提示：先确认收入与支出的时间范围一致。', '', '| 项目 | 金额 |', '| --- | ---: |', '| 收入 | 100 |', '| 支出 | 60 |', '', '```flow', '开始 -> 员工提交申请', '员工提交申请 -> 主管审批', '主管审批 -> 判断天数', '判断天数 ->|是（<=3天）| 主管批准', '判断天数 ->|否（>3天）| 部门经理审批', '主管批准 -> 结束1', '部门经理审批 -> 经理判断', '经理判断 ->|批准| 结束2', '经理判断 ->|驳回| 结束3', '```', '', '```chart', 'type: bar', 'title: 示例收支', '收入 | 100', '支出 | 60', '```', '', '```python', 'balance = 100 - 60', 'print(balance)', '```'].join('\n');
    const output = payload.messages[0].content.includes('教学配图编辑') && !input.revisionRequest ? {needed:true,reason:'一张场景图有助于建立直观认识。',prompt:'无文字的日常消费教学插图，强调收入与支出的差异',caption:'图片帮助理解收支场景，不代表精确数值。'}
      : payload.messages[0].content.includes('学习需求访谈顾问') ? {scope:'focused',known:['希望用 Python 编写文件整理工具'],gaps:[{dimension:'优先整理的文件类型',reason:'决定练习案例'},{dimension:'希望交付的工具形式',reason:'决定验收任务'}]}
      : payload.messages[0].content.includes('自学课程顾问') ? planningQuestionnaire
      : input.daily !== undefined ? {...demoPlan,title:'路线纠正集成测试',lessons:input.repair ? demoPlan.lessons : [demoPlan.lessons[0]]}
      : input.revisionRequest ? {text:markdownAnswer}
      : input.notes ? {answer:'## 检索结论\n\n**输入与输出**已记录在你的知识卡片中。',citations:[input.notes[0].id]}
      : input.sourceText ? {title:'现金流',summary:'**现金流**的核心概念与实践方法',content:wikiMarkdown,tags:['财务'],useWhen:['分析收支时'],avoidWhen:[]}
      : input.lesson && input.reflection !== undefined ? {summary:'**现金流**的核心概念与实践方法',content:wikiMarkdown}
      : {answer:chatMarkdown};
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ choices: [{ message: { content: JSON.stringify(output) }, finish_reason: 'stop' }] }));
  });
  await new Promise(resolve => model.listen(0, '127.0.0.1', resolve));
  try {
    const modelUrl = `http://127.0.0.1:${model.address().port}/v1`;
    const changed = await evaluate(`window.learnflowDesktop.saveSettings(${JSON.stringify({ provider: 'compatible', model: 'smoke-chat-model', baseUrl: modelUrl, keyAction: 'clear', apiKey: '', localOnly: true, jsonMode: 'auto', timeoutMs: 120000, maxTokens: 8192 })})`);
    assert.equal(changed.status.mode, 'ai');
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate("document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id=p1]').click()");
    await wait("document.querySelector('[data-tab=chat]')");
    await evaluate("document.querySelector('[data-tab=chat]').click(); document.querySelector('#lesson-question').value = '什么是输出？'; document.querySelector('#lesson-ask-form').requestSubmit()");
    await wait("document.querySelector('.chat-message.from-ai')?.textContent.includes('显示给用户') && !document.querySelector('#lesson-ask-form button[type=submit]').disabled");
    await store.flush();
    assert.equal(requests.length, 1);
    assert.equal(requests[0].path, '/v1/chat/completions');
    assert.equal(JSON.parse(requests[0].payload.messages[1].content).question, '什么是输出？');
    const chatted = await store.loadState();
    assert.equal(chatted.chats.p1.at(-2).content, '什么是输出？');
    assert.equal(chatted.chats.p1.at(-1).content, chatMarkdown);
    assert.equal(await evaluate("document.querySelector('.chat-message.from-ai:last-child .markdown-content h3').textContent"), '直接回答');
    assert.ok(await evaluate("!!document.querySelector('.chat-message.from-ai:last-child pre code')"));
    assert.equal(await evaluate("getComputedStyle(document.querySelector('.chat-message.from-ai:last-child .markdown-content strong')).display"), 'inline');
    await evaluate("document.querySelector('[data-page=wiki]').click(); document.querySelector('[data-view=chat]').click(); document.querySelector('#wiki-question').value = '输入与输出有哪些要点？'; document.querySelector('#ask-form').requestSubmit()");
    await wait("document.querySelector('.grounded-answer .answer-body h3')?.textContent === '检索结论' && !document.querySelector('#ask-form button[type=submit]').disabled");
    assert.equal(await evaluate("document.querySelector('.grounded-answer .markdown-content strong').textContent"), '输入与输出');
    assert.ok(await evaluate("!!document.querySelector('.grounded-answer .citation')"));
    // Reproduce a one-course response and exercise the corrected retry through the real planner.
    await evaluate("document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=planner]').click(); document.querySelector('#goal').value = '用 Python 编写自动整理文件的小工具'; document.querySelector('#plan-form').requestSubmit()");
    await wait("document.querySelector('#clarification-form')");
    assert.equal(await evaluate("document.querySelectorAll('#clarification-form input:checked').length"),0);
    await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await writeFile(path.join(directory,'..','planner-questions-smoke.png'),(await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('[name=q1][value=o1]').click(); document.querySelector('[name=q2][value=unsure]').click(); document.querySelector('[name=q2][value=o1]').click()");
    assert.equal(await evaluate("document.querySelector('[name=q2][value=unsure]').checked"),false);
    await evaluate("document.querySelector('#detail-q1').value = '先学习安全预览，再执行文件移动'; document.querySelector('#detail-q1').dispatchEvent(new Event('input',{bubbles:true})); document.querySelector('#clarification-form').requestSubmit()");
    await wait("document.querySelector('#plan-confirm-form')");
    await evaluate("document.querySelector('[data-action=planner-back]').click()");
    assert.equal(await evaluate("document.querySelector('[name=q1][value=o1]').checked"),true);
    assert.equal(await evaluate("document.querySelector('#detail-q1').value"),'先学习安全预览，再执行文件移动');
    await evaluate("document.querySelector('#clarification-form').requestSubmit()");
    await wait("document.querySelector('#plan-confirm-form')");
    await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await writeFile(path.join(directory,'..','planner-review-smoke.png'),(await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('#planner-notes').value = '不学习网页开发'; document.querySelector('#plan-confirm-form').requestSubmit()");
    await wait("!document.querySelector('#planner').open && document.querySelector('.route-overview h2')?.textContent === '路线纠正集成测试'");
    const planRequests = requests.map(request => JSON.parse(request.payload.messages[1].content)).filter(input => input.daily !== undefined && input.learningBrief);
    assert.equal(planRequests.length, 2);
    assert.equal(planRequests[1].repair.receivedLessonCount, 1);
    assert.equal(planRequests[1].goal, planRequests[0].goal);
    const planned = await store.loadState();
    assert.equal(planned.plans.find(plan => plan.id === planned.active).lessons.length, demoPlan.lessons.length);
    assert.equal(planned.plans.find(plan => plan.id === planned.active).learningBrief.notes,'不学习网页开发');
    assert.equal(planRequests[1].learningBrief.answers[0].detail,'先学习安全预览，再执行文件移动');
    assert.ok(await evaluate("!!document.querySelector('.route-design details')"));
    // Test grouped teaching and feedback regeneration on a fresh, isolated lesson.
    const { randomUUID } = require('node:crypto');
    const route = structuredClone(demoPlan);
    route.id = randomUUID(); route.source = 'ai'; route.title = '讲解与案例桌面测试';
    route.lessons = route.lessons.map(lesson => ({...lesson, id:randomUUID()}));
    const lessonId = route.lessons[0].id;
    await evaluate(`window.learnflowDesktop.savePlan(${JSON.stringify(route)})`);
    const course = await evaluate(`window.learnflowDesktop.saveOutline(${JSON.stringify(lessonId)}, ${JSON.stringify({intro:'独立集成测试课程', blocks:[
      {type:'reading',title:'理解现金流',objective:'理解收支与余额'},
      {type:'example',title:'日常收支案例',objective:'计算剩余现金'},
      {type:'quiz',title:'检验理解',objective:'独立作答'}
    ]})})`);
    const readingId = course.blocks[0].id, exampleId = course.blocks[1].id;
    await evaluate(`window.learnflowDesktop.saveBlock(${JSON.stringify(lessonId)}, ${JSON.stringify(readingId)}, {text:'原始讲解：认识现金流。'})`);
    await evaluate(`window.learnflowDesktop.saveBlock(${JSON.stringify(lessonId)}, ${JSON.stringify(exampleId)}, {text:'配套案例：收入 100 元，支出 60 元。'})`);
    await evaluate(`window.learnflowDesktop.saveProgress(${JSON.stringify(lessonId)}, {completed:true,attempts:1,lastScore:100,bestScore:100,lastAnswers:[0],updated:1234})`);
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('.teaching-unit .teaching-example')");
    assert.equal(await evaluate("document.querySelector('.teaching-unit').querySelectorAll('.teaching-part').length"), 2);
    const unitHeightBeforeMenu = await evaluate("document.querySelector('.teaching-unit').getBoundingClientRect().height");
    await evaluate("document.querySelector('.teaching-reading .more-learning-tools summary').click()");
    await wait("document.querySelector('.teaching-reading .more-learning-tools').open");
    const dropdownLayout = await evaluate("(() => { const unit = document.querySelector('.teaching-unit'); const menu = unit.querySelector('.teaching-reading .more-learning-tools-menu'); return { unitHeight:unit.getBoundingClientRect().height, position:getComputedStyle(menu).position, overflow:getComputedStyle(unit).overflow, visible:menu.getBoundingClientRect().height > 0 }; })()");
    assert.equal(dropdownLayout.position, 'absolute');
    assert.equal(dropdownLayout.overflow, 'visible');
    assert.equal(dropdownLayout.visible, true);
    assert.ok(Math.abs(dropdownLayout.unitHeight - unitHeightBeforeMenu) <= 1, 'dropdown should overlay rather than stretch the lesson card');
    await evaluate("document.querySelector('.teaching-reading .more-learning-tools').scrollIntoView({block:'start'}); new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    await writeFile(path.join(directory, '..', 'learning-tools-dropdown-smoke.png'), (await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('.teaching-reading .block-title').click()");
    await wait("!document.querySelector('.teaching-reading .more-learning-tools').open");
    await evaluate("document.querySelector('.teaching-reading [data-action=toggle-block-collapse]').click()");
    assert.equal(await evaluate("document.querySelector('.teaching-reading .block-collapsible-body').hidden"), true);
    assert.equal(await evaluate("document.querySelector('.teaching-example .block-collapsible-body').hidden"), false);
    await evaluate("document.querySelector('.teaching-example [data-action=toggle-block-collapse]').click()");
    assert.equal(await evaluate("document.querySelector('.teaching-example .block-collapsible-body').hidden"), true);
    await evaluate("document.querySelector('.teaching-reading [data-action=toggle-block-collapse]').click(); document.querySelector('.teaching-example [data-action=toggle-block-collapse]').click()");
    await evaluate(`document.querySelector('[data-action=request-revision][data-block="${readingId}"]').click()`);
    await wait("document.querySelector('#revise-block-dialog').open");
    await evaluate("document.querySelector('[data-action=markdown-revision-preset]').click()");
    assert.match(await evaluate("document.querySelector('#revision-request').value"), /请仅优化.*Markdown/);
    await evaluate("document.querySelector('#revision-request').value = '术语太多，请用收支表逐步计算并解释'; document.querySelector('#revision-form').requestSubmit()");
    await wait("!document.querySelector('#revise-block-dialog').open && document.querySelector('.teaching-reading .block-text').textContent.includes('剩余现金 40 元')");
    const revised = await store.loadState();
    assert.equal(revised.blockCourses[lessonId].blocks[0].content.revisions[0].text, '原始讲解：认识现金流。');
    assert.equal(revised.blockCourses[lessonId].blocks[1].content.text, '配套案例：收入 100 元，支出 60 元。');
    assert.equal(revised.progress[lessonId].completed, true);
    assert.deepEqual(revised.notes, chatted.notes);
    assert.equal(JSON.parse(requests.at(-1).payload.messages[1].content).revisionRequest, '术语太多，请用收支表逐步计算并解释');
    const typography = await evaluate("(() => { const body = document.querySelector('.teaching-reading .markdown-content'); return { heading:body.querySelector('h3')?.textContent, subheading:body.querySelector('h4')?.textContent, strong:body.querySelector('strong')?.textContent, steps:body.querySelectorAll('ol > li').length, table:!!body.querySelector('table'), code:!!body.querySelector('pre code'), quote:!!body.querySelector('blockquote'), bodyWhiteSpace:getComputedStyle(body).whiteSpace, headingSize:parseFloat(getComputedStyle(body.querySelector('h3')).fontSize), textSize:parseFloat(getComputedStyle(body.querySelector('p')).fontSize) }; })()");
    assert.equal(typography.heading, '核心结论');
    assert.equal(typography.subheading, '计算步骤');
    assert.equal(typography.strong, '剩余现金 40 元');
    assert.equal(typography.steps, 2);
    assert.ok(typography.table && typography.code && typography.quote);
    assert.equal(typography.bodyWhiteSpace, 'normal');
    assert.ok(typography.headingSize > typography.textSize);
    assert.equal(await evaluate("document.querySelector('.teaching-reading .markdown-content svg, .teaching-reading .learning-visual, .teaching-reading .visual-fallback') === null"), true);
    assert.match(await evaluate("document.querySelector('.teaching-reading pre code.language-flow').textContent"), /判断天数 ->\|是（<=3天）\| 主管批准/);
    assert.match(await evaluate("document.querySelector('.teaching-reading pre code.language-chart').textContent"), /收入 \| 100/);
    assert.match(revised.blockCourses[lessonId].blocks[0].content.text, /```chart/);
    await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await writeFile(path.join(directory, '..', 'teaching-smoke.png'), (await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('.teaching-reading pre code.language-flow').scrollIntoView({block:'center'})");
    await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await writeFile(path.join(directory, '..', 'legacy-code-smoke.png'), (await window.webContents.capturePage()).toPNG());
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('.teaching-reading pre code.language-chart')");
    assert.equal(await evaluate("document.querySelector('.teaching-reading .markdown-content svg') === null"), true);
    // A failed regeneration keeps both the original text and the feedback field.
    await evaluate(`document.querySelector('[data-action=request-revision][data-block="${exampleId}"]').click()`);
    await evaluate("document.querySelector('#revision-request').value = '测试模型不可用'; document.querySelector('#revision-form').requestSubmit()");
    await wait("document.querySelector('#revision-error').textContent.length > 0 && !document.querySelector('#revision-form button[type=submit]').disabled");
    assert.equal(await evaluate("document.querySelector('#revise-block-dialog').open"), true);
    assert.equal(await evaluate("document.querySelector('#revision-request').value"), '测试模型不可用');
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks[1].content.text, '配套案例：收入 100 元，支出 60 元。');
    await writeFile(path.join(directory, '..', 'feedback-smoke.png'), (await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('[data-action=close-revision]').click()");
    // Exercise restoration through IPC and then reload from the actual SQLite file.
    await evaluate(`window.learnflowDesktop.restoreBlock(${JSON.stringify(lessonId)}, ${JSON.stringify(readingId)}, ${JSON.stringify(revised.blockCourses[lessonId].blocks[0].content.text)})`);
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('.teaching-reading .block-text')?.textContent.includes('原始讲解')");
    assert.equal(await evaluate("document.querySelector('[data-action=restore-block]') === null"), true);
    // Independently configure image service through the real settings form.
    await evaluate("document.querySelector('[data-page=settings]').click()");
    await evaluate(`document.querySelector('#image-settings-form [name=enabled]').checked = true; document.querySelector('#image-model-name').value = 'smoke-image-model'; document.querySelector('#image-model-url').value = ${JSON.stringify(modelUrl)}; document.querySelector('#image-key-action').value = 'replace'; document.querySelector('#image-model-key').value = 'smoke-image-key-not-real'; document.querySelector('#image-size').value = '64x64'; document.querySelector('#image-settings-form').requestSubmit()`);
    await wait("document.querySelector('#image-connection-result')?.textContent.includes('图片配置已保存')");
    const imageConfiguration = await readFile(path.join(directory,'image-settings.json'),'utf8');
    assert.ok(!imageConfiguration.includes('smoke-image-key-not-real'));
    assert.equal((await evaluate('window.learnflowDesktop.load()')).imageSettings.apiKey, undefined);
    await evaluate("document.querySelector('[data-action=check-image-connection]').click()");
    await wait("document.querySelector('#image-connection-result')?.textContent.includes('未生成图片')");
    assert.equal(imageRequests.length,0);
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('[data-action=request-illustration]')");
    await evaluate(`document.querySelector('[data-action=request-illustration][data-block="${readingId}"]').click()`);
    await wait("document.querySelector('#illustration-prompt')?.value.includes('教学插图') && !document.querySelector('#illustration-form fieldset').disabled");
    assert.equal(imageRequests.length,0,'suggesting an image must not generate or charge for one');
    await evaluate("document.querySelector('#illustration-prompt').value = '故障测试'; document.querySelector('#illustration-form').requestSubmit()");
    await wait("document.querySelector('#illustration-error')?.textContent.includes('503') && !document.querySelector('#illustration-form button[type=submit]').disabled");
    assert.equal(imageRequests.length,1,'generation failure must not auto-retry');
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks[0].content.illustration,undefined);
    await evaluate("document.querySelector('#illustration-prompt').value = '无文字教学示意'; document.querySelector('#illustration-form').requestSubmit()");
    await wait("!document.querySelector('#illustration-dialog').open && document.querySelector('.course-illustration img')?.complete && document.querySelector('.course-illustration img')?.naturalWidth === 64");
    assert.equal(imageRequests.length,2);
    const withImage = (await store.loadState()).blockCourses[lessonId].blocks[0].content;
    assert.equal(withImage.text,'原始讲解：认识现金流。');
    assert.ok(withImage.illustration.id);
    assert.equal(withImage.illustration.model,'smoke-image-model');
    assert.ok(!await evaluate("document.cookie.includes('learnflow-assets')"));
    const assetUrl = await evaluate("document.querySelector('.course-illustration img').src");
    assert.equal((await fetch(assetUrl)).status,403,'asset cookie is required outside the app');
    await evaluate(`window.learnflowDesktop.reviseBlock(${JSON.stringify(lessonId)},${JSON.stringify(readingId)},{text:'新正文不应该沿用旧图'},${JSON.stringify(withImage.text)})`);
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks[0].content.illustration,undefined);
    await evaluate(`window.learnflowDesktop.restoreBlock(${JSON.stringify(lessonId)},${JSON.stringify(readingId)},'新正文不应该沿用旧图')`);
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load',resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('.course-illustration img')?.complete && document.querySelector('.course-illustration img')?.naturalWidth === 64");
    assert.equal(imageRequests.length,2,'reload and restoration must reuse the local file');
    await wait("document.querySelector('.course-illustration img')?.getBoundingClientRect().height > 50");
    await evaluate("document.querySelector('.course-illustration').scrollIntoView({block:'start'}); new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))");
    await writeFile(path.join(directory,'..','illustration-smoke.png'),(await window.webContents.capturePage()).toPNG());
    // Switch protocols using the actual UI; only a local native-protocol mock is contacted.
    await evaluate("document.querySelector('[data-page=settings]').click(); document.querySelector('#image-protocol').value='dashscope'; document.querySelector('#image-protocol').dispatchEvent(new Event('change',{bubbles:true}))");
    assert.equal(await evaluate("document.querySelector('#image-response-format').disabled"),true);
    assert.equal(await evaluate("document.querySelector('#image-model-key').value"),'');
    assert.equal(await evaluate("document.querySelector('[data-action=check-image-connection]').disabled"),true);
    // Reproduce the exact reported Token Plan root, saving only a fake key.
    // Do not click connection or generation until the service is local again.
    await evaluate("document.querySelector('#image-settings-form [name=enabled]').checked=true; document.querySelector('#image-model-name').value='wan2.7-image-pro'; document.querySelector('#image-model-url').value='https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1'; document.querySelector('#image-settings-form [name=localOnly]').checked=false; document.querySelector('#image-key-action').value='replace'; document.querySelector('#image-model-key').value='smoke-token-plan-key-not-real'; document.querySelector('#image-size').value='1024x1024'; document.querySelector('#image-settings-form').requestSubmit()");
    await wait("document.querySelector('#image-connection-result')?.textContent.includes('同域名的 /api/v1')");
    const tokenSaved=(await evaluate('window.learnflowDesktop.load()')).imageSettings;
    assert.equal(tokenSaved.baseUrl,'https://token-plan.cn-beijing.maas.aliyuncs.com/api/v1');
    assert.equal(tokenSaved.protocol,'dashscope');assert.equal(tokenSaved.hasApiKey,true);assert.equal(tokenSaved.apiKey,undefined);
    assert.equal(await evaluate("document.querySelector('#image-settings-error').textContent"),'');
    const tokenFile=await readFile(path.join(directory,'image-settings.json'),'utf8');
    assert.ok(!tokenFile.includes('smoke-token-plan-key-not-real'));assert.ok(JSON.parse(tokenFile).encryptedApiKey.length>0);
    assert.equal(nativeRequests.length,0);assert.equal(nativeChecks,0);assert.equal(nativeDownloads,0);
    window.webContents.reload();await new Promise(resolve=>window.webContents.once('did-finish-load',resolve));
    await wait("document.querySelector('main h1')");await evaluate("document.querySelector('[data-page=settings]').click()");
    assert.equal(await evaluate("document.querySelector('#image-model-url').value"),tokenSaved.baseUrl);
    assert.equal(await evaluate("document.querySelector('#image-protocol-hint').textContent.includes('此提醒不阻止保存')"),true);
    await evaluate("document.querySelector('#image-settings-form [name=localOnly]').checked=true");
    await evaluate(`document.querySelector('#image-model-name').value='wan2.7-image-pro'; document.querySelector('#image-model-url').value=${JSON.stringify(modelUrl.replace(/\/v1$/,'/compatible-mode/v1'))}; document.querySelector('#image-key-action').value='replace'; document.querySelector('#image-model-key').value='smoke-native-key-not-real'; document.querySelector('#image-size').value='1024x1024'; document.querySelector('#image-settings-form').requestSubmit()`);
    await wait("document.querySelector('#image-connection-result')?.textContent.includes('图片配置已保存')");
    const nativeConfiguration=await readFile(path.join(directory,'image-settings.json'),'utf8');
    assert.equal(JSON.parse(nativeConfiguration).protocol,'dashscope');assert.ok(!nativeConfiguration.includes('smoke-native-key-not-real'));
    assert.equal(JSON.parse(nativeConfiguration).baseUrl,modelUrl.replace(/\/v1$/,'/api/v1'));
    window.webContents.reload();await new Promise(resolve=>window.webContents.once('did-finish-load',resolve));
    await wait("document.querySelector('main h1')");await evaluate("document.querySelector('[data-page=settings]').click()");
    assert.equal(await evaluate("document.querySelector('#image-protocol').value"),'dashscope');
    assert.equal(await evaluate("document.querySelector('#image-response-format').disabled"),true);
    await evaluate("document.querySelector('[data-action=check-image-connection]').click()");
    await wait("document.querySelector('#image-connection-result')?.textContent.includes('已在列表中找到模型')");
    assert.equal(nativeChecks,1);assert.equal(nativeRequests.length,0);
    await evaluate("document.querySelector('.image-settings-panel').scrollIntoView({block:'start'}); new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))");
    assert.equal(await evaluate("document.documentElement.scrollWidth <= innerWidth + 1"),true,'native settings hints should not cause horizontal overflow');
    await writeFile(path.join(directory,'..','bailian-settings-smoke.png'),(await window.webContents.capturePage()).toPNG());
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait(`document.querySelector('[data-action=request-illustration][data-block="${readingId}"]')`);
    await evaluate(`document.querySelector('[data-action=request-illustration][data-block="${readingId}"]').click()`);
    await wait("document.querySelector('#illustration-form') && document.querySelector('#illustration-dialog').open");
    await evaluate("document.querySelector('#illustration-prompt').value='原生故障测试'; document.querySelector('#illustration-form').requestSubmit()");
    await wait("document.querySelector('#illustration-error')?.textContent.includes('InvalidParameter') && !document.querySelector('#illustration-form button[type=submit]').disabled");
    const nativeError=await evaluate("document.querySelector('#illustration-error').textContent");
    assert.ok(!nativeError.includes('smoke-native-key-not-real'));assert.ok(!nativeError.includes('private upstream prompt'));
    assert.equal(nativeRequests.length,1);assert.equal(nativeDownloads,0);
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks[0].content.illustration.model,'smoke-image-model','native failure preserves the old illustration');
    await evaluate("document.querySelector('#illustration-prompt').value='下载故障测试'; document.querySelector('#illustration-form').requestSubmit()");
    await wait("document.querySelector('#illustration-download-notice') && document.querySelector('#illustration-error')?.textContent.includes('503') && !document.querySelector('#illustration-form fieldset').disabled");
    assert.equal(nativeRequests.length,2);assert.equal(nativeDownloads,1);
    assert.ok(!await evaluate("document.querySelector('#illustration-dialog').innerHTML.includes('private-mock-signature')"));
    const retained=await evaluate(`window.learnflowDesktop.getPendingIllustration(${JSON.stringify(lessonId)},${JSON.stringify(readingId)})`);
    assert.equal(retained.pendingDownload.host,'127.0.0.1');assert.equal(retained.url,undefined);
    const repeated=await evaluate(`window.learnflowDesktop.generateIllustration(${JSON.stringify({lessonId,blockId:readingId,expectedText:withImage.text,expectedImageId:withImage.illustration.id,prompt:'不应再次计费',caption:'测试'})})`);
    assert.equal(repeated.pendingDownload.id,retained.pendingDownload.id);assert.equal(nativeRequests.length,2,'pending downloads must block another generation');
    await evaluate("document.querySelector('[data-action=close-illustration]').click()");
    await evaluate(`document.querySelector('[data-action=request-illustration][data-block="${readingId}"]').click()`);
    await wait("document.querySelector('#illustration-dialog').open && document.querySelector('#illustration-download-notice')");
    assert.equal(await evaluate("document.querySelector('#illustration-prompt').readOnly"),true);
    assert.equal(await evaluate("document.querySelector('#illustration-form button[type=submit]').textContent"),'仅重试下载（不重新生成）');
    assert.equal(nativeRequests.length,2);
    await evaluate('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))');
    await writeFile(path.join(directory,'..','image-download-retry-smoke.png'),(await window.webContents.capturePage()).toPNG());
    await evaluate("document.querySelector('#illustration-form').requestSubmit()");
    await wait("!document.querySelector('#illustration-dialog').open && document.querySelector('.course-illustration img')?.naturalWidth===64");
    const nativeContent=(await store.loadState()).blockCourses[lessonId].blocks[0].content;
    assert.equal(nativeContent.text,withImage.text);assert.equal(nativeContent.illustration.model,'wan2.7-image-pro');
    assert.equal(nativeRequests.length,2);assert.equal(nativeDownloads,2);assert.equal(imageRequests.length,2,'native mode must never fall back to a paid compatible request');
    assert.equal(await evaluate(`window.learnflowDesktop.getPendingIllustration(${JSON.stringify(lessonId)},${JSON.stringify(readingId)})`),null);
    window.webContents.reload();await new Promise(resolve=>window.webContents.once('did-finish-load',resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait("document.querySelector('.course-illustration img')?.naturalWidth===64");
    assert.equal(nativeRequests.length,2);assert.equal(nativeDownloads,2,'reloading uses the local image, not the cloud URL');
    // A private download token cannot outlive its course content or source service.
    const retrySettings=(await evaluate('window.learnflowDesktop.load()')).imageSettings;
    const retryBlock=await evaluate(`window.learnflowDesktop.appendBlock(${JSON.stringify(lessonId)},{type:'reading',title:'下载重试版本保护',objective:'验证下载结果不会覆盖更新内容'})`);
    await evaluate(`window.learnflowDesktop.saveBlock(${JSON.stringify(lessonId)},${JSON.stringify(retryBlock.id)},{text:'下载重试原文'})`);
    const retryValue={lessonId,blockId:retryBlock.id,expectedText:'下载重试原文',expectedImageId:'',prompt:'下载故障测试',caption:'重试保护测试'};
    const servicePending=await evaluate(`window.learnflowDesktop.generateIllustration(${JSON.stringify(retryValue)})`);
    assert.ok(servicePending.pendingDownload);assert.equal(nativeRequests.length,3);assert.equal(nativeDownloads,3);
    assert.equal(await evaluate(`window.learnflowDesktop.getPendingIllustration(${JSON.stringify(lessonId)},${JSON.stringify(readingId)})`),null,'another block cannot access this token');
    await evaluate(`window.learnflowDesktop.saveImageSettings(${JSON.stringify({...retrySettings,baseUrl:retrySettings.baseUrl.replace('127.0.0.1','localhost'),keyAction:'clear',apiKey:''})})`);
    const serviceError=await evaluate(`window.learnflowDesktop.retryIllustrationDownload(${JSON.stringify({lessonId,blockId:retryBlock.id,pendingId:servicePending.pendingDownload.id})}).then(()=>null,error=>error.message)`);
    assert.match(serviceError,/服务已更改/);assert.equal(nativeRequests.length,3);assert.equal(nativeDownloads,3);
    await evaluate(`window.learnflowDesktop.saveImageSettings(${JSON.stringify({...retrySettings,keyAction:'replace',apiKey:'smoke-native-key-not-real'})})`);
    const textPending=await evaluate(`window.learnflowDesktop.generateIllustration(${JSON.stringify(retryValue)})`);
    assert.ok(textPending.pendingDownload);assert.equal(nativeRequests.length,4);assert.equal(nativeDownloads,4);
    await evaluate(`window.learnflowDesktop.reviseBlock(${JSON.stringify(lessonId)},${JSON.stringify(retryBlock.id)},{text:'下载重试新正文'},'下载重试原文')`);
    const staleError=await evaluate(`window.learnflowDesktop.retryIllustrationDownload(${JSON.stringify({lessonId,blockId:retryBlock.id,pendingId:textPending.pendingDownload.id})}).then(()=>null,error=>error.message)`);
    assert.match(staleError,/课程／服务已更改/);assert.equal(nativeRequests.length,4);assert.equal(nativeDownloads,4);
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks.find(block=>block.id===retryBlock.id).content.text,'下载重试新正文');
    console.log('IMAGE_DOWNLOAD_SMOKE',JSON.stringify({passed:true,checks:['download-failure-preserves-old-image','pending-token-no-signed-url','download-only-retry-no-paid-post','dialog-close-reopen-reuses-result','source-change-and-stale-content-blocked']}));
    console.log('BAILIAN_NATIVE_SMOKE',JSON.stringify({passed:true,checks:['protocol-ui-save-reload-encryption','native-model-list-no-generation','native-error-no-retry-no-key-leak','native-payload-url-download-no-key','native-image-local-persistence-no-fallback']}));
    // Practice has the same three assistance actions, without changing quizzes.
    const practiceBlock = await evaluate(`window.learnflowDesktop.appendBlock(${JSON.stringify(lessonId)}, {type:'practice',title:'会议听力任务',objective:'独立记录会议进度'})`);
    const practiceText = "## 实践任务\n\n听两遍模拟会议材料，记录每个人的进度。\n\n```text\nSarah: Alright, let's get started.\nMark: I've finished the login page.\nLisa: I'll wrap it up tomorrow.\n```";
    await evaluate(`window.learnflowDesktop.saveBlock(${JSON.stringify(lessonId)}, ${JSON.stringify(practiceBlock.id)}, {text:${JSON.stringify(practiceText)}})`);
    window.webContents.reload(); await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click(); document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait(`document.querySelector('[data-block-id="${practiceBlock.id}"] [data-action=request-revision]')`);
    const practiceActions = await evaluate(`Array.from(document.querySelectorAll('[data-block-id="${practiceBlock.id}"] .revision-actions button')).map(button=>({action:button.dataset.action,text:button.textContent}))`);
    assert.deepEqual(practiceActions.map(button=>button.action),['create-note','request-illustration','request-revision']);
    assert.equal(practiceActions[2].text,'换个任务');
    await evaluate(`document.querySelector('[data-block-id="${practiceBlock.id}"]').scrollIntoView({block:'center'}); document.querySelector('.quick-speech-button').click()`);
    await wait("document.querySelector('#speech-dialog').open && !document.querySelector('#speech-preview-fields').disabled");
    assert.match(await evaluate("document.querySelector('#speech-material').value"),/^Sarah: Alright/);
    assert.equal(await evaluate("document.querySelector('#speech-material').value.includes('实践任务')"),false);
    await evaluate("document.querySelector('[data-action=close-speech]').click()");
    const practicePostsBefore = nativeRequests.length;
    await evaluate(`document.querySelector('[data-action=request-illustration][data-block="${practiceBlock.id}"]').click()`);
    await wait("document.querySelector('#illustration-prompt')?.value.includes('日常消费') && !document.querySelector('#illustration-form fieldset').disabled");
    assert.equal(nativeRequests.length,practicePostsBefore,'practice image suggestions do not generate an image');
    await evaluate("document.querySelector('#illustration-form').requestSubmit()");
    await wait(`!document.querySelector('#illustration-dialog').open && document.querySelector('[data-block-id="${practiceBlock.id}"] .course-illustration img')?.complete`);
    assert.equal(nativeRequests.length,practicePostsBefore+1);
    const practiceImage = (await store.loadState()).blockCourses[lessonId].blocks.find(block=>block.id===practiceBlock.id).content.illustration;
    assert.equal(practiceImage.model,'wan2.7-image-pro');
    await evaluate(`document.querySelector('[data-action=request-revision][data-block="${practiceBlock.id}"]').click()`);
    assert.equal(await evaluate("document.querySelector('#revise-block-title').textContent"),'按你的需求调整实践任务');
    await evaluate("document.querySelector('#revision-request').value='降低听力任务难度，并提供明确的完成标准'; document.querySelector('#revision-form').requestSubmit()");
    await wait("!document.querySelector('#revise-block-dialog').open");
    const practiceRevised=(await store.loadState()).blockCourses[lessonId].blocks.find(block=>block.id===practiceBlock.id).content;
    assert.equal(practiceRevised.illustration,undefined);
    assert.equal(practiceRevised.revisions[0].text,practiceText);
    assert.equal(practiceRevised.revisions[0].illustration.id,practiceImage.id);
    const practiceRequest=JSON.parse(requests.at(-1).payload.messages[1].content);
    assert.equal(practiceRequest.block.type,'practice');assert.equal(practiceRequest.block.objective,'独立记录会议进度');
    // Supply the test user's explicit confirmation without opening a blocking
    // native confirm dialog in this hidden automated test window.
    await evaluate(`(() => { const previousConfirm=window.confirm; try { window.confirm=()=>true; document.querySelector('[data-action=restore-block][data-block="${practiceBlock.id}"]').click(); } finally { window.confirm=previousConfirm; } })()`);
    await wait(`document.querySelector('[data-block-id="${practiceBlock.id}"] .block-text')?.textContent.includes('模拟会议材料')`);
    assert.equal((await store.loadState()).progress[lessonId].completed,true);
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks.find(block=>block.id===practiceBlock.id).content.illustration.id,practiceImage.id);
    await evaluate(`document.querySelector('[data-block-id="${practiceBlock.id}"]').scrollIntoView({block:'start'}); new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
    await writeFile(path.join(directory,'..','practice-actions-smoke.png'),(await window.webContents.capturePage()).toPNG());
    window.webContents.reload();await new Promise(resolve=>window.webContents.once('did-finish-load',resolve));await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=routes]').click();document.querySelector('[data-action=open-lesson][data-id="${lessonId}"]').click()`);
    await wait(`document.querySelector('[data-block-id="${practiceBlock.id}"] .course-illustration img')?.complete`);
    assert.equal((await store.loadState()).blockCourses[lessonId].blocks.find(block=>block.id===practiceBlock.id).content.text,practiceText);
    console.log('PRACTICE_ACTIONS_SMOKE',JSON.stringify({passed:true,checks:['three-block-actions-and-floating-speech','practice-transcript-preview','image-confirmation-and-IPC-save','task-feedback-and-history','restore-task-and-image','quiz-progress-preserved','sqlite-reload']}));
    // Generate an AI Wiki card and verify that source Markdown survives a renderer reload.
    await evaluate("document.querySelector('.teaching-reading details').open=true; document.querySelector('.teaching-reading [data-action=create-note]').click()");
    await wait("document.querySelector('#knowledge-draft-form')");
    await evaluate("document.querySelector('#knowledge-draft-form').requestSubmit()");
    await wait("document.querySelector('#note-preview-content h3')?.textContent === '核心概念'");
    assert.equal(await evaluate("document.querySelector('#note-preview-content strong').textContent"), '现金流');
    const aiNote = (await store.loadState()).notes.find(note => note.lessonId === lessonId);
    assert.equal(aiNote.content, wikiMarkdown);
    window.webContents.reload();
    await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
    await wait("document.querySelector('main h1')");
    await evaluate(`document.querySelector('[data-page=wiki]').click(); document.querySelector('[data-action=open-note][data-id="${aiNote.id}"]').click()`);
    await wait("document.querySelector('#note-preview-content h3')?.textContent === '核心概念'");
    assert.equal(await evaluate("document.querySelector('#note-content').value"), wikiMarkdown);
  } finally {
    model.closeAllConnections();
    await new Promise(resolve => model.close(resolve));
  }
  await evaluate(`window.learnflowDesktop.saveSettings(${JSON.stringify({ ...localSettings, model: 'desktop-smoke-model' })})`);
  await evaluate(`window.learnflowDesktop.saveImageSettings(${JSON.stringify({...imageDefaults,keyAction:'clear',apiKey:''})})`);
  window.webContents.reload();
  await new Promise(resolve => window.webContents.once('did-finish-load', resolve));
  await wait("document.querySelector('main h1')");
  await require('./quality-smoke.cjs').run(window, directory);
  await require('./speech-smoke.cjs').run(window, directory);
  await evaluate("document.querySelector('#speech-dialog').close()");
  await evaluate("document.querySelector('[data-page=settings]').click()");
  await wait("document.querySelector('#desktop-settings-form')");
  await evaluate("window.scrollTo({top:0,behavior:'instant'})");
  const image = await window.webContents.capturePage();
  await writeFile(path.join(directory, '..', 'settings-smoke.png'), image.toPNG());
  console.log('DESKTOP_SMOKE', JSON.stringify({ passed: true, checks: ['window', 'sandbox', 'settings-save', 'os-encryption', 'cloud-save-confirmation', 'cloud-settings-reload', 'lan-save-confirmation', 'quick-ask-right-dock-and-focus', 'quick-ask-return-position', 'quiz', 'wiki', 'knowledge-tree-chat-and-graph', 'disk-persistence', 'reload', 'lesson-qa', 'adaptive-learning-questionnaire-and-confirmation', 'plan-invalid-count-repair', 'teaching-unit', 'independent-block-collapse', 'floating-learning-tools-dropdown', 'feedback-regeneration', 'markdown-typography', 'legacy-diagram-fences-as-code-reload', 'markdown-revision-preset', 'learning-note-tab-removed-and-card-creation', 'note-markdown-read-edit', 'chat-markdown', 'grounded-markdown-citations', 'ai-wiki-markdown-reload', 'revision-failure-preserves-content', 'revision-restore-reload', 'image-settings-os-encryption', 'image-model-check-without-generation', 'image-suggestion-before-confirmation', 'image-generation-failure-no-retry', 'image-local-render-layout-and-reload', 'image-restoration-with-text', 'private-asset-cookie'], screenshot: path.join(directory, '..', 'settings-smoke.png') }));
};
